### PR TITLE
Katex support

### PR DESCRIPTION
**Pull request by steinwaywhw**
* Mainly focus on moving from `marked` to `markdown-it`. This one supports CommonMark, which is a super set of markdown.
* Katex is added for `markdown-it-math` to render Latex expression at server end. However, Katex is still very limited compared to MathJax. (But MathJax is not server end)
* Some style change. (Please ignore this one if you don't like it by not cheery picking this commit.)
* Some misc changes, like Dockerfile and gitignore.

### CODE REVIEW

**Comment by mrtnbroder** [comment]
A lot of stuff seems to be broken, like dropdowns etc. Also, please create a seperate PR for style changes (which, I dont agree with though.) If you state 'Katex support' but also add/change styles, the adjust the title.

**Comment by steinwaywhw** [comment]
Yes you are right. I'm sorry for that and let me figure out how to separate them.

**Comment by steinwaywhw** [comment]
Hi @mrtnbroder, I went back all the way back to b5ff521b332c3c1e37869b75c5f07a109685b4b9 and the dropdown still didn't work. It's not due to my change. And frankly speaking, I didn't find out why. It doesn't fire `click` event at all. I'm suspecting the dropdown related javascript didn't initialize correctly. Please take a look. Thanks

**Comment by misterbisson** [comment]
@mrtnbroder The issue with dropdowns has been reported in a few issues previously, though I think  https://github.com/joemccann/dillinger/issues/297 is the most detailed.

**Pull request closed without merging**
