### PR TITLE
Small Docker improvements

### PR DESCRIPTION
**Pull request by misterbisson**
Changes following resolution of https://github.com/joemccann/dillinger/issues/296 and https://github.com/joemccann/dillinger/issues/309, though the problems identified in https://github.com/joemccann/dillinger/issues/297 remain.

I've registered this in Docker Hub at https://registry.hub.docker.com/u/misterbisson/dillinger/, though I'd recommend creating an official entry for it.

To run:

`docker run -d -p 80:80 misterbisson/dillinger`

~~Example container running (for now):~~

~~http://165.225.186.212~~

### CODE REVIEW

**Comment by misterbisson** [comment]
@joemccann note the bug still outstanding (https://github.com/joemccann/dillinger/issues/297), but I think that's independent of the Dockerfile.

See example running at http://165.225.186.212/

**Comment by misterbisson** [comment]
Bump @joemccann

**Comment by joemccann** [comment]
Sorry will check asap

On Wednesday, April 22, 2015, Casey Bisson <notifications@github.com> wrote:

> Bump @joemccann <https://github.com/joemccann>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joemccann/dillinger/pull/313#issuecomment-95397919>.
>


-- 
Sent from Joe In Real Life

**Comment by joemccann** [comment]
Try doublechecking the issue with #297 as it should be fixed now that we've upgraded the angular version.  If that works out fine, LMK and I'll merge it

**Comment by misterbisson** [comment]
Sorry for the delay @joemccann. I just confirmed that I'm in sync with origin master and I'm still seeing the issues named in https://github.com/joemccann/dillinger/issues/297. 

I do get the following warnings when building:

```
WARNING in bundle.js from UglifyJs
Dropping unused variable arg [./~/exports-loader?angular!./~/angular/angular.js:49,0]
Dropping unused variable logMsg [./~/exports-loader?angular!./~/angular/angular.js:14260,0]
Dropping unreachable code [./~/exports-loader?angular!./~/angular/angular.js:16860,0]
Dropping unused function includes [./~/exports-loader?angular!./~/angular/angular.js:708,0]
Dropping unused function nodesetLinkingFn [./~/exports-loader?angular!./~/angular/angular.js:8320,0]
Dropping unused function directiveLinkingFn [./~/exports-loader?angular!./~/angular/angular.js:8327,0]
Condition always true [./~/jquery/dist/jquery.js:9165,0]
Dropping unused function isPrimitive [./~/brace/index.js:918,0]
Dropping unused function toPrimitive [./~/brace/index.js:929,0]
Side effects in initialization of unused variable dom [./~/brace/index.js:2346,0]
Side effects in initialization of unused variable event [./~/brace/index.js:2347,0]
Side effects in initialization of unused variable useragent [./~/brace/index.js:2348,0]
Side effects in initialization of unused variable oop [./~/brace/index.js:2588,0]
Side effects in initialization of unused variable old [./~/brace/index.js:3376,0]
Non-strict equality against boolean: != true [./~/brace/index.js:3997,0]
Non-strict equality against boolean: != true [./~/brace/index.js:3997,0]
Dropping unreachable code [./~/brace/index.js:5695,0]
Side effects in initialization of unused variable sel [./~/brace/index.js:5740,0]
Side effects in initialization of unused variable oop [./~/brace/index.js:6574,0]
Side effects in initialization of unused variable afterEnd [./~/brace/index.js:7114,0]
Side effects in initialization of unused variable consumedFolds [./~/brace/index.js:7119,0]
Side effects in initialization of unused variable Range [./~/brace/index.js:7051,0]
Non-strict equality against boolean: == true [./~/brace/index.js:10001,0]
Non-strict equality against boolean: != false [./~/brace/index.js:10002,0]
Non-strict equality against boolean: == false [./~/brace/index.js:10026,0]
Non-strict equality against boolean: == false [./~/brace/index.js:10043,0]
Dropping unused function last [./~/brace/index.js:11090,0]
Side effects in initialization of unused variable end [./~/brace/index.js:11722,0]
Non-strict equality against boolean: != false [./~/brace/index.js:13747,0]
Side effects in initialization of unused variable useragent [./~/brace/index.js:13339,0]
Non-strict equality against boolean: == true [./~/brace/index.js:16997,0]
Side effects in initialization of unused variable oop [./~/brace/index.js:17687,0]
Side effects in initialization of unused variable Range [./~/brace/index.js:17689,0]
Side effects in initialization of unused variable Range [./~/brace/mode/markdown.js:903,0]
Side effects in initialization of unused variable lang [./~/brace/mode/markdown.js:1199,0]
Side effects in initialization of unused variable lang [./~/brace/mode/markdown.js:1358,0]
Side effects in initialization of unused variable lang [./~/brace/mode/markdown.js:1628,0]
Side effects in initialization of unused variable Behaviour [./~/brace/mode/markdown.js:1772,0]
Condition always true [./~/marked/lib/marked.js:1262,0]
Dropping unreachable code [./~/marked/lib/marked.js:1264,1]
Condition always true [./~/highlight.js/lib/highlight.js:10,0]
Dropping unreachable code [./~/highlight.js/lib/highlight.js:15,0]
Dropping unused variable IDENT_RE [./~/highlight.js/lib/languages/haxe.js:2,0]
Dropping unused variable dollarEscape [./~/highlight.js/lib/languages/powershell.js:6,0]
Dropping unused variable JAVADOC [./~/highlight.js/lib/languages/scala.js:44,0]
Dropping unused variable REGULAR_EXPRESSION [./~/highlight.js/lib/languages/scheme.js:66,0]
Side effects in initialization of unused variable DEF_INTERNALS [./~/highlight.js/lib/languages/scss.js:17,0]
[16:28:21] Finished 'webpack:build' after 3.1 min
```

In looking at [my build steps](https://github.com/misterbisson/dillinger/blob/master/Dockerfile), is there anything that pops out as incorrect?

Two demo locations:

1. self-built: http://72.2.118.89
2. automatically built by [Docker HUB](https://registry.hub.docker.com/u/misterbisson/dillinger/): http://165.225.188.197

**Comment by joemccann** [comment]
not sure, tbh

**Comment by misterbisson** [comment]
@joemccann: it looks like @steinwaywhw has [tracked down](https://github.com/joemccann/dillinger/pull/321#issuecomment-100315452) the root cause of the issue in https://github.com/joemccann/dillinger/issues/297: https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md#breaking-changes

Can we consider merging this as it appears the two are unrelated?

**Comment by joemccann** [comment]
done, pushed to prod...thanks!

**Comment by misterbisson** [comment]
Woot, thanks @joemccann!

I'm happy to remove [my entry in Docker Hub for this](https://registry.hub.docker.com/u/misterbisson/dillinger/) if you want to create an [automated](https://docs.docker.com/docker-hub/builds/#linking-your-docker-hub-account-to-a-github-account), canonical build. Docs: https://docs.docker.com/docker-hub/builds/#linking-your-docker-hub-account-to-a-github-account, or just start here: https://registry.hub.docker.com/associate/github/ .

**Pull request merged**
