### PR TITLE
Set the current document title to the first title in pasted text

### PR DESCRIPTION
**Pull request by dwaq**
PR for #645 

1. Register a listener to Ace's paste event
2. Check that the document is still untitled
3. If so, register a one-time listener on `preview.updated` to detect when the Markdown is parsed
4. Find the first header in the Markdown (if there is one) and set the Document's title to it

I had to pull in the documentsService to the user controller to read and write the document's title

I also tried to make it work while typing but it wasn't easy to detect when a header line is complete and should be selected as the title. If this is a desired feature, do you have any ideas on how to complete it?

### CODE REVIEW

**Comment by joemccann** [comment]
Another great addition! Reviewing now.

**Comment by joemccann** [comment]
Ok this is great!  I'm going to push this live but can you add `.md` to the H1 after it is found?  Need to still name it a markdown file.

**Comment by joemccann** [comment]
Meaning, if the first H1 is "My Cool Title" the title of the doc becomes "My Cool Title.md"

**Comment by dwaq** [comment]
Yeah, I understand. Is that really necessary though? I noticed if I export the file as a Markdown, it automatically adds the ".md". The same is true if I export to Dropbox (I haven't tried the other services). Is there another location where this matters?

**Comment by joemccann** [comment]
Yeah good point -- I don't recall if when it is saved to Dropbox or Drive,
etc. it automatically appends the .md or not.  I would just want to ensure
that it always has the file extension and by adding it here it more or less
accomplishes it...that's the idea behind it

**Pull request merged**
