### PR TITLE
Feature addition.  Custom Github messages and Travis-ci skip ci option.

### PR DESCRIPTION
**Pull request by june07**
Fulfills Issue "Custom GitHub commit message. #208"

Live version can be seen here:
http://dillinger.june07.com:8080/

### CODE REVIEW

**Comment by joemccann** [comment]
First, this is great work!  Thanks so much for contributing this.

On first glance, the UI is the only part we need to improve.  Ideally, the GitHub custom message is a modal notification in the flow of Saving to GitHub, not something that persists in the UI all the time.  Also, the current layout breaks on mobile or tablet devices so adding it to the modal userflow makes the most sense.

The logic is all correct, but we need to find a way to make the message come up in a modal notification.

**Comment by joemccann** [comment]
Something messy happened with `public/css/app.css`

**Comment by june07** [comment]
See commit 4e83d887dfb8eb268d67f0e17864cac5509a1e7a

I think that's the reason public/css/app.css was funky.  I've updated http://dillinger.june07.com:8080/ with the most recent commit.

**Comment by joemccann** [comment]
Awesome contribution! thanks!

**Pull request merged**
