### PR TITLE
Makes Travis CI produce and deploy pre-built .zip and .tar.gz archives

### PR DESCRIPTION
**Pull request by benjamin-albert**
This pull request adds the `dist` task to gulp which produces a pre-built zip archive.

It also removes `gulp build --prod` as a postinstall script.

At first I wanted to use `.tar.gz` but then I remembered that `.tar.gz` requires a third party utility to extract on windows and `.zip` doesn't.

I don't think there is any reason to produce two formats (like GitHub does).

I also updated the installation instructions in the Readme to explain how to install from a pre-built release.

### When you make a release:

Produce a zip file with all the necessary files (including `bundle.js` and `app.css`).

    $ gulp build dist --prod

[Create a release](https://github.com/joemccann/dillinger/releases) on GitHub and attach the `pre-built.zip` file as a binary.

I'm looking into Travis-CI creating and attaching the pre-built zip to a release for us.   More info on this coming soon.

### CODE REVIEW

**Comment by joemccann** [comment]
We need to create `tar` and `zip` if we want x-platform support.  

Also, we need this to be automated, not a manual step, meaning, a new release should be generated automatically as opposed to me having to upload a zip file to github every time.

**Comment by benjamin-albert** [comment]
I have no problem producing both formats, but seeing as 

> Most popular Linux distros these days are by default equipped with zip compatibility.
> If you only need 85%, zip will do fine.

I thought that just producing `.zip` will do just fine.

Source [On Linux/Unix, does .tar.gz versus .zip matter?](http://superuser.com/a/146758/226926) on Super User.

**Comment by benjamin-albert** [comment]
Usually good GitHub releases consist of brief description of the new release.

Can you think of an algorithm for producing good release descriptions automatically?

Usually maintainers make the description by taking the titles (or first few lines) of the pull requests that make up the release.

But even if we can come up with a program that collects just the PR that make up the new release you will still need to brush up the description.

I think having a brief summery of what each released includes can be useful for both the 100+ users that are watching the repo and us maintainers/developers.

I am more then willing to draft the releases each time you deploy to dillinger.io.

What I'm thinking is a good idea is to draft the release on GitHub and have Travis-CI produce and attach the tar/zip files to the release.

@joemccann Tell me what you think.

**Comment by benjamin-albert** [comment]
As I've mentioned before I Made the `dist` task produce both `.zip` and `.tar.gz` archives.

I also made the all the necessary setup for Travis CI to:
1. Generate the pre-built .zip and .tar.gz archives.
2. Upload the archives to GitHub releases whenever we draft a release (push a tag).

**So how does it work now?**
1. Merge some pull requests/make some commits.
2. Draf a release on GitHub.
3. Watch Travis CI do the rest  (generate and upload the archives to GitHub).

**Please note:**
The `.travis.yml` uses an encrypted oauth token generated using my account.

As far as I can tell I don't see any reason that deployment to GitHub won't work when deploying to your repo, but it's probably a good idea to generate your own oauth token.

You ca install the [Travis CI command line client](https://github.com/travis-ci/travis.rb#installation) and use:

    travis setup releases

Which generates and encrypts the token for you.

Please make sure that all the `deploy` configuration is kept as is.

For more details about Travis CI GitHub deploy see: 
https://docs.travis-ci.com/user/deployment/releases.

**Comment by joemccann** [comment]
this is awesome..will test it soon

**Pull request merged**
