### PR TITLE
BUGFIX Upgrade Dropbox to v2 API

### PR DESCRIPTION
**Pull request by js-kyle**

### CODE REVIEW

**Comment by joemccann** [comment]
Nice work. Reviewing now.

**Comment by joemccann** [comment]
Okay so the Authentication piece and saving files works great!  Awesome work.

The issue I'm having is searching.

Now, I am running on `localhost` but have the auth url, etc. pointed to `localhost` for now.

When I search:

screen shot 2018-02-04 at 07 52 17

But the response comes back:

screen shot 2018-02-04 at 07 54 11

Repro:  Authenticated then attempt to import a markdown file from Dropbox.

**Comment by js-kyle** [comment]
@joemccann Hmm, I can't reproduce this one on my environment (works ok). I'll keep looking into why this could be happening though

**Comment by joemccann** [comment]
Ok thx

**Comment by js-kyle** [comment]
@joemccann I've submitted a new PR which refactors this area and surfaces the errors if encountered. Give that one a spin, https://github.com/joemccann/dillinger/pull/672/files

**Pull request merged**
