### PR TITLE
Makes PDF export 10 times faster and fixes #503

### LINKED ISSUE #503: Export as PDF renders someone else's markdown document
Last week I completed a homework assignment on dillinger.io and exported it to PDF in order to submit it. I received an email later on telling me that I had submitted the wrong file — in fact, the file that was exported to me was not my assignment, but rather a Dillinger-styled document titled "TP2 : Découverte du CSS3 et du SCSS I: CSS3". I haven't been able to replicate the error, but I believe that I was served a file that belongs to someone else. For what it's worth, I'm using Chrome 48.0.2564.109 on OS X 10.11. I'd rather not post either document publicly, but I'm happy to provide them over email and help in whatever way I can to resolve this issue. Thanks for your attention.

### PR DESCRIPTION
**Pull request by benjamin-albert**
Hi,
I was using Dillinger to write my Résumé and export it to PDF.

When I export the document to PDF I noticed a light gray background that I really didn't like.

When I found out the project is on GitHub I was delighted because I could just fix that myself.

When I cloned the project to my local machine I noticed a few other things that could be improved.

This pull request refactors document export to use a single `POST` request instead of having one `POST` request for processing and one `GET` request for downloading the results.

Using a single `POST` request for both processing and downloading allows us to avoid writing temp files for HTML and Markdown exporting by piping the results to the response.

I also made the PDF export run 10 times faster by creating a single instance of PhantomJS on startup and reusing it for all PDF export requests.

This pull request also fixes #503 by:
1. writing the temp files generated during the PDF export to the system temp folder and giving them unique names.
2. Deleting the unnecessary downloads directory.

You can easily end up with someone else's document (as described in #503) by opening Dillinger and editing different documents on two separate machines and **clicking Export to PDF at the same time**.  Try it yourself at http://dillinger.io/.

As I've mentioned above I removed the light gray background around the content
in the PDF exporting by changing `$c-background` to `#fff` in `public/scss/foundation/_config.scss`.

~~**I couldn't manage to run the tests** using `karma start` as described in the
projects README. This is probably something I'm doing wrong.  I'll discuss this
in a separate issue.~~

**Update:** I've managed to run the tests, see [comment below](https://github.com/joemccann/dillinger/pull/511#issuecomment-195967175).

Thanks for an amazing markdown editor :)

### CODE REVIEW

**Comment by benjamin-albert** [comment]
Update: I've managed to run the tests.

I installed `karma` globally instead of `karma-cli`.  After installing `karma-cli` looks like all test are passing.

```
Safari 9.0.3 (Mac OS X 10.11.3): Executed 19 of 19 SUCCESS (0.477 secs / 0.44 secs)
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 19 of 19 SUCCESS (0.322 secs / 0.316 secs)
Firefox 47.0.0 (Mac OS X 10.11.0): Executed 19 of 19 SUCCESS (0.429 secs / 0.409 secs)
Chrome 49.0.2623 (Mac OS X 10.11.3): Executed 19 of 19 SUCCESS (0.442 secs / 0.427 secs)
TOTAL: 76 SUCCESS
```

**Comment by joemccann** [comment]
holy :hankey: this is an amazing PR!  thanks!

**Comment by joemccann** [comment]
updated on dillinger.io

**Comment by benjamin-albert** [comment]
Your welcome 😀

It looks Safari and Chrome are serving up a cached (stale) version of the js bundle which breaks the export for existing users. 

Hopefully you can do something about this before users start opening issues about this.

**Pull request merged**
