### PR TITLE
Feature Add - Bitbucket Plugin

### PR DESCRIPTION
**Pull request by june07**
So currently the code only has read functionality due to the shortcomings of the Bitbucket REST API.  Unlike the GitHub REST API, Bitbucket's does not allow for pushing repo changes.  See this link for more info:
[https://answers.atlassian.com/questions/33129483/do-you-having-an-api-to-push-the-content-to-bitbucket-repo](https://answers.atlassian.com/questions/33129483/do-you-having-an-api-to-push-the-content-to-bitbucket-repo).

Write functionality is gonna require a different approach.

### CODE REVIEW

**Comment by june07** [comment]
Forgot to add this link: http://dillinger.june07.com:8080

**Comment by joemccann** [comment]
Amazing!  Will review ASAP!

**Comment by joemccann** [comment]
@june07 Getting an error:

screen shot 2017-02-26 at 18 59 47

When trying to import a markdown issue from BitBucket, this is the issue:

`TypeError: o.config.orgs.push is not a function`

Also, I've never used BitBucket but I created an account, created a test repo here as well:

https://bitbucket.org/joemccann/dillinger-test-repo

**Comment by june07** [comment]
Just created a brand new test Bitbucket account and imported using the test site:
http://dillinger.june07.com:8080

It worked fine on my end.

I'm going to try to duplicate the same problem but so far I'm unable to.  Can I ask how you tested?  I mean it looks as if the domain used was "dillinger.io" but I'm sure that was a dev server or something and not the live site?  Can I access the dev site somehow?

**Comment by june07** [comment]
Joe,

I took a closer look at this and think I know what is happening.  Ill give it a closer look today and test with a brand new account vs my own.

**Comment by joemccann** [comment]
great thanks!

**Comment by june07** [comment]
So your problem was likely that you didn't have the correct permissions set on your OAuthconsumer key.  I've attached screenshots.  You must have the "Team membership" Read checkbox selected.  Then when a user confirms Bitbucket account access they will see the message as shown in the second screenshot.

capture

capture2

I am updating the plugin README to include the same info now.

Further, I also found a bug (unrelated to this issue) which should now be fixed.

I will be submitting a new pull request shortly for said changes.

**Pull request merged**
