### PR TITLE
[WIP] update to angular-bootstrap 0.12.0 and fix related bugs

### PR DESCRIPTION
**Pull request by JuanCaicedo**
I replicated #296 and think that it would be worth updating to angular-bootstrap 0.12.0 to fix this problem. However, this new version breaks a few things, as mentioned in #297. The fix for this was mentioned in [this issue from the original project](angular-ui/bootstrap#3094), which I have implemented.

I can verify that the "export as" menu is working, but not the "import as" or "save to" menus. The structure for these is also different, it's a ul inside the dropdown. Any thoughts on how to test them?

### CODE REVIEW

**Comment by dandavison** [comment]
Thanks @JuanCaicedo!

> I can verify that the "export as" menu is working, but not the "import as" or "save to" menus.

Confirm that on @JuanCaicedo's branch. Also the "Services" dropdown doesn't seem to respond to clicks; I was hoping to try out the "link to google doc" functionality.

**Comment by joemccann** [comment]
So I'm confused. Does this work or break things?

**Comment by JuanCaicedo** [comment]
It's breaking right now. It's a work in progress becausethe other two menus
seem to work differently and don't respond to the same fix.. Any tips on
how to test them?

**Comment by joemccann** [comment]
Test the UI?  I would see what deltas exist, if any, between the various menus.

**Pull request closed without merging**
